require: rubocop-rails
AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'spec/**/*'
    - 'app/controllers/**'
    - 'app/graphql/reviews_schema.rb'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Style/Documentation:
  Enabled: false
Style/MutableConstant:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
Rails/EnumHash:
  Enabled: false
